openapi: 3.0.0
info:
  title: TaskFlow API
  description: API documentation for the TaskFlow project management system
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /projects:
    get:
      summary: Get all projects
      responses:
        "200":
          description: A list of projects
    post:
      summary: Create a new project
      responses:
        "201":
          description: Project created
  /tasks:
    get:
      summary: Get all tasks
      responses:
        "200":
          description: A list of tasks
    post:
      summary: Create a new task
      responses:
        "201":
          description: Task created
